apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-data-pvc
      containers:
        - name: log-generator
          image: sakuheinonen/log-output:generator-1.11
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/files
        - name: log-reader
          image: sakuheinonen/log-output:reader-1.11
          ports:
            - containerPort: 3030
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              value: "3030"