apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-app
  namespace: exercises
  labels:
    app: ping-pong-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-app
  template:
    metadata:
      namespace: exercises
      name: ping-pong-app
      labels:
        app: ping-pong-app
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
        - name: ping-pong-app
          image: sakuheinonen/ping-pong:3.1.3
          env:
            - name: PORT
              value: "3050"
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD