apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-app
  namespace: exercises
  labels:
    app: ping-pong-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-app
  template:
    metadata:
      namespace: exercises
      name: ping-pong-app
      labels:
        app: ping-pong-app
    spec:
      containers:
        - name: ping-pong-app
          image: sakuheinonen/ping-pong:2.1
          env:
            - name: PORT
              value: "3050"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"