apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
resources:
  - ../manifests/deployment.yaml
  - ../manifests/service.yaml
  - ../manifests/postgres-service.yaml
  - ../manifests/postgres-db.yaml
  - ../manifests/postgres-config.yaml