apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-data-pv
  namespace: project
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/shared-data
  storageClassName: manual