apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster-service
  labels:
    app: broadcaster-service
spec:
  replicas: 6
  selector:
    matchLabels:
      app: broadcaster-service
  template:
    metadata:
      labels:
        app: broadcaster-service
    spec:
      serviceAccountName: discord-bot-sa
      containers:
        - name: broadcaster-service
          image: europe-west4-docker.pkg.dev/dauntless-glow-470207-m2/my-repository/broadcaster-service
          env:
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: NATS_URL
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "100m"
