apiVersion: v1
kind: Service
metadata:
  name: todo-backend-svc
spec:
  selector:
    app: todo-backend
  ports:
    - protocol: TCP
      targetPort: 3000
      name: http
      port: 2345
  type: ClusterIP
  