apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-backend
  labels:
    app: todo-app-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-backend
  template:
    metadata:
      name: todo-app-backend
      labels:
        app: todo-app-backend
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-data-pvc
      containers:
        - name: todo-app-backend
          image: sakuheinonen/todo-backend:1.13
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/files
          env:
            - name: BACKEND_PORT
              value: "3000"
            - name: IMAGE_DIR
              value: "/usr/src/app/files/images"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"