apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-app-frontend
  labels:
    app: todo-app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-frontend
  template:
    metadata:
      namespace: project
      name: todo-app-frontend
      labels:
        app: todo-app-frontend
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-data-pvc
      containers:
        - name: todo-app-frontend
          image: europe-west4-docker.pkg.dev/dauntless-glow-470207-m2/my-repository/frontend
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/files
          env:
            - name: IMAGE_SERVICE_PORT
              value: "3000"
            - name: PROD
              value: "true"