apiVersion: v1
kind: Service
metadata:
  name: todo-app-frontend-svc
spec:
  selector:
    app: todo-app-frontend
  ports:
    - protocol: TCP
      targetPort: 80
      name: http
      port: 80
  type: ClusterIP
  