apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
  labels:
    app: image-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      name: image-service
      labels:
        app: image-service
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-data-pvc
      containers:
        - name: image-service
          image: sakuheinonen/image-service:2.2
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              value: "3000"
            - name: IMAGE_DIR
              value: "/usr/src/app/files/image"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"