apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: image-service
  labels:
    app: image-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      namespace: project
      name: image-service
      labels:
        app: image-service
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-data-pvc
      containers:
        - name: image-service
          image: sakuheinonen/image-service:3.5.1
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              value: "3000"
            - name: GIN_MODE
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: GIN_MODE
            - name: ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: ALLOWED_ORIGINS
            - name: CACHE_DURATION_MINUTES
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: CACHE_DURATION_MINUTES
            - name: IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: IMAGE_URL
            - name: IMAGE_DIR
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: IMAGE_DIR
            - name: CACHED_IMAGE_NAME
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: CACHED_IMAGE_NAME