name: debug.yaml
on:
  workflow_dispatch:

jobs:
  debug-secrets:
    name: Debug Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug secrets length
        run: |
          echo "GKE_SA_KEY length: $(echo '${{ secrets.GKE_SA_KEY }}' | wc -c) }}')"
          echo "$(echo '${{ vars }}')"
