name: GitOps Deploy Staging

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CREDENTIALS: ${{ secrets.GKE_SA_KEY }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-west4-a
  REGISTRY: europe-west4-docker.pkg.dev
  REPOSITORY: my-repository
  ARCHITECTURE: linux/amd64
  ENVIRONMENT: staging
  DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

jobs:
  build-and-deploy:
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0

      - name: Set image tags
        id: set_outputs
        run: |
          echo "frontend_image=${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/frontend:${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "todo_service_image=${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/todo-service:${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "image_service_image=${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/image-service:${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "broadcaster_service_image=${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/broadcaster-service:${{ github.sha }}" >> $GITHUB_OUTPUT

      - uses: google-github-actions/auth@v3
        with:
          credentials_json: "${{ env.GKE_CREDENTIALS }}"

      - uses: google-github-actions/setup-gcloud@v3

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGISTRY }} --quiet

      - uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.ARCHITECTURE }}

      - name: Build & Push Images
        run: |
          docker buildx build --platform ${{ env.ARCHITECTURE }} -t ${{ steps.set_outputs.outputs.frontend_image }} --push ./todo-app/frontend
          docker buildx build --platform ${{ env.ARCHITECTURE }} -t ${{ steps.set_outputs.outputs.todo_service_image }} --push ./todo-app/backend/todo-service
          docker buildx build --platform ${{ env.ARCHITECTURE }} -t ${{ steps.set_outputs.outputs.image_service_image }} --push ./todo-app/backend/image-todo-service
          docker buildx build --platform ${{ env.ARCHITECTURE }} -t ${{ steps.set_outputs.outputs.broadcaster_service_image }} --push ./todo-app/backend/broadcaster-todo-service

      - uses: actions/checkout@v5.0.0

      - uses: google-github-actions/auth@v3
        with:
          credentials_json: "${{ env.GKE_CREDENTIALS }}"

      - uses: google-github-actions/setup-gcloud@v3

      - uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: "${{ env.GKE_CLUSTER }}"
          project_id: "${{ env.PROJECT_ID }}"
          location: "${{ env.GKE_ZONE }}"

      - uses: imranismail/setup-kustomize@v2.1.0

      - name: Deploy to Staging
        run: |
          kubectl create namespace ${{ env.ENVIRONMENT }} || true
          kubectl config set-context --current --namespace=${{ env.ENVIRONMENT }}
          cd todo-app/kubernetes/overlays/staging
          kustomize edit set image ${{ steps.set_outputs.outputs.frontend_image }}
          kustomize edit set image ${{ steps.set_outputs.outputs.todo_service_image }}
          kustomize edit set image ${{ steps.set_outputs.outputs.image_service_image }}
          kustomize edit set image ${{ steps.set_outputs.outputs.broadcaster_service_image }}
          kustomize build . | kubectl apply -f -
          kubectl set env deployment/broadcaster-service DISCORD_WEBHOOK_URL=${{ env.DISCORD_WEBHOOK_URL }} -n ${{ env.ENVIRONMENT }}
          kubectl rollout status deployment/broadcaster-service -n ${{ env.ENVIRONMENT }}

      - name: Commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: "./kubernetes/kustomization.yaml"
          message: New version released ${{ github.sha }}
